language: c

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: 6.6
    - RACKET_VERSION: 6.7
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --installation --auto --link
      $TRAVIS_BUILD_DIR/hackett-lib
      $TRAVIS_BUILD_DIR/hackett-test
  - raco pkg install --installation --auto cover cover-coveralls

script:
  - raco test -ep hackett-lib hackett-test
  - raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p hackett-lib hackett-test
