language: c

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: 6.8
    - RACKET_VERSION: 6.9
    - RACKET_VERSION: HEAD

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --installation --auto --link
      $TRAVIS_BUILD_DIR/hackett-demo
      $TRAVIS_BUILD_DIR/hackett-lib
      $TRAVIS_BUILD_DIR/hackett-test

script:
  - raco test -ep hackett-demo hackett-lib hackett-test
